### ISSUE TITLE
Windows port?

### ISSUE THREAD

**Issue by FirebrandCoding** [fespinoza/LinkedIdeas#114]
Linked Ideas looks *amazing* for the kind of a thought process I often go through. Usually, I'd use a sticky paper – a small, finite medium that doesn't support editing (naturally) – to make these kinds of links. This would be tremendous to have.

Unfortunately, I can't use it on Windows, 'cause it's a Mac/iOS app. I recognize this is a longshot, but: is it possible for Linked Ideas to be ported to Windows? I know I could run a virtual machine and/or make my laptop a Hackintosh, but – hopefully, it's already clear how much superior a native experience is. Besides, I'm sure I'm not the only one to enjoy what is a promisingly-beneficial tool.

I don't presume you owe doing the additional work of porting the app to anyone, and I recognize that it isn't an easy task. But, on the off-chance that you're interested in making it happen, Linked Ideas sounds like a worthy addition to the small, but growing arsenal of the new generation of minimalist knowledge workers.

**Comment by fespinoza** [comment]
Thank you for the kind feedback, unfortunately i am not interested in porting linked ideas to windows as I only use apple devices, linked ideas was a hobby project that i built for myself and wanted to share with other people.

If there is anyone who wants to take the projects of making a linked ideas or similar port to windows I would be happy to help on a conceptual level, as i don't have window desktop dev experience.

**Comment by FirebrandCoding** [comment]
That's fair.

If someone does take on porting the app, please notify me: I'd be thrilled to test and use it.

(Also, I'm not quite sure how issue-closing works, so if my comment re-opens it, I apologize: I didn't intend to.)
