### ISSUE TITLE
App crash/freeze when linking nodes

### ISSUE THREAD

**Issue by peterschussheim** [fespinoza/LinkedIdeas#121]
Hi Felipe,

Thanks for LinkedIdeas, I just discovered it and was trying out the linking functionality when the application 'froze', requiring me to quit.  Screenshot added.  Please let me know what kind of debug info (if any) to provide.

<img width="862" alt="LinkedIdeas001-frozen" src="https://user-images.githubusercontent.com/3654683/66511511-14254100-eaa5-11e9-9889-f8d9ff692601.png">

**Comment by fespinoza** [comment]
thanks for the report! I will check if i can reproduce or If i get any stacktrace from apple :)

**Comment by fespinoza** [comment]
I will release the patch later during the day, i'm sorry for the bug

**Comment by peterschussheim** [comment]
Thanks Felipe!
