### ISSUE TITLE
Liking the idea

### ISSUE THREAD

**Issue by setegonz** [fespinoza/LinkedIdeas#79]
Do you have an instructions file?

**Comment by fespinoza** [comment]
not right now, here are the list of possible actions right now:

- double click on canvas -> create concept in place
- double click on concept -> edits it
- click on concept -> selects it
- shift + drag on canvas -> multiple select concepts under area
- shift + drag on concept to another -> create link
- shift + enter -> creates concept at random place
- drag concept -> changes its position
- alt+shift+ number (1 to 7) -> sets predefined colors into the concept's text
- alt+command+"+" -> increase size of selected concepts
- alt+command+e -> strikethrough the selected concepts.

i am working on making the UI better and experimenting still, so then i will create a better tutorial

**Comment by setegonz** [comment]
Thanks!
